gravity_compensation_controller:
  ros__parameters:
    type: pal_controllers/GravityCompensationController

    command_joints: ['arm_left_1_joint', 'arm_left_2_joint', 'arm_left_3_joint', 'arm_left_4_joint', 'arm_left_5_joint', 'arm_left_6_joint', 'arm_left_7_joint', 'arm_right_1_joint', 'arm_right_2_joint', 'arm_right_3_joint', 'arm_right_4_joint', 'arm_right_5_joint', 'arm_right_6_joint', 'arm_right_7_joint']

    root_link: "torso_lift_link"

    tip_links: ["${EE_TIP_LINK_LEFT}", "${EE_TIP_LINK_RIGHT}"]

    torque_gain: 1.0

    parameters:
      arm_left_1_joint:
        motor_torque_constant: 0.0
        reduction_ratio: 100.0
        kp: 6.0
        kd: 1.0
      arm_left_2_joint:
        motor_torque_constant: 0.136
        reduction_ratio: 100.0
        kp: 6.0
        kd: 0.8
      arm_left_3_joint:
        motor_torque_constant: -0.087
        reduction_ratio: 100.0
        kp: -6.0
        kd: -0.8
      arm_left_4_joint:
        motor_torque_constant: -0.087
        reduction_ratio: 100.0
        kp: -6.0
        kd: -0.8
      arm_left_5_joint:
        motor_torque_constant: -1.0
        reduction_ratio: 336.0
        kp: -0.02
        kd: -0.02
      arm_left_6_joint:
        motor_torque_constant: 0.0
        reduction_ratio: 336.0
        kp: 0.2
        kd: 0.02
      arm_left_7_joint:
        motor_torque_constant: 0.0
        reduction_ratio: 336.0
        kp: 0.2
        kd: 0.02
      arm_right_1_joint:
        motor_torque_constant: 0.0
        reduction_ratio: 100.0
        kp: 6.0
        kd: 1.0
      arm_right_2_joint:
        motor_torque_constant: 0.136
        reduction_ratio: 100.0
        kp: 6.0
        kd: 0.8
      arm_right_3_joint:
        motor_torque_constant: -0.087
        reduction_ratio: 100.0
        kp: -6.0
        kd: -0.8
      arm_right_4_joint:
        motor_torque_constant: -0.087
        reduction_ratio: 100.0
        kp: -6.0
        kd: -0.8
      arm_right_5_joint:
        motor_torque_constant: -1.0
        reduction_ratio: 336.0
        kp: -0.02
        kd: -0.02
      arm_right_6_joint:
        motor_torque_constant: 0.0
        reduction_ratio: 336.0
        kp: 0.2
        kd: 0.02
      arm_right_7_joint:
        motor_torque_constant: 0.0
        reduction_ratio: 336.0
        kp: 0.2
        kd: 0.02        
