/joy_teleop:
  use_preset: "joy_teleop_parallel_gripper_right.yaml"
  use_if:
    end_effector_right: robotiq-2f-140

  ros__parameters:

    close_gripper_right:
      action_goal:
        increment_by: [0.1]
    
    open_gripper_right:
      action_goal:
        increment_by: [-0.1]